name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang

    # - name: Install dependencies (macOS)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew install cmake clang

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake llvm --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: powershell

    - name: Configure CMake with Clang
      run: cmake --preset tests

    - name: Build
      run: cmake --build --preset tests

    - name: Run tests
      run: ctest --preset tests
      continue-on-error: false
